### ISSUE TITLE
Better installation error message

### ISSUE THREAD

**Issue by luqmaan** [getsentry/sentry-hipchat-ac#15]
I get an error when installing the Sentry for Hipchat integration. Unfortunately the error message isn't descriptive at all, so I can't figure out how to debug it.

![image](https://cloud.githubusercontent.com/assets/1275831/11067018/2416ea40-8790-11e5-8b59-337fe7af3318.png)

POST https://abcdef.hipchat.com/apiv2/addons?room_id=666

```
{
  "error": {
    "code": "400",
    "message": "Failed to install addon: The add-on rejected the installation: 500 INTERNAL SERVER ERROR",
    "type": "Bad Request"
  }
}
```

**Comment by mitsuhiko** [comment]
Is that an on-premise installation you are using?

**Comment by luqmaan** [comment]
No, this is hosted HipChat.

**Comment by mitsuhiko** [comment]
I mean of sentry. Are you using the sentry installation on getsentry.com or your own?

**Comment by luqmaan** [comment]
getsentry.com. Also, we're using the old HipChat integration for a bunch of projects from https://app.getsentry.com/team/my-project/settings/plugins/hipchat/

**Comment by mitsuhiko** [comment]
For the new hipchat connect API we unfortunately have very little information about why installation fails. That dialog we have no control over which makes logging hard.  I checked our logs and we do not have a failure logged in the new plugin for this part.  Can you maybe open a support request at getsentry.com with your organization and failing project and I debug it there?

**Comment by luqmaan** [comment]
Sounds good, I just opened a support request there. Our account slug is teamordoro.

**Comment by mitsuhiko** [comment]
This is up to Atlassian unfortunately.
