### ISSUE TITLE
On-Premise Dockerized Sentry and Sentry-hipchat-ac plugin error

### ISSUE THREAD

**Issue by ykravch** [getsentry/sentry-hipchat-ac#25]
Hello.
I've installed https://github.com/getsentry/docker-sentry Sentry 8.2.3 with sentry-hipchat-ac plugin by adding pip install https://github.com/getsentry/sentry-hipchat-ac/archive/master.zip to Dockerfile.
After sentry upgrade when I go to project's configuration page (Projects -> [Project]) and enable "HipChat with Atlassian Connect" I receive an error:
`ProgrammingError: relation "sentry_hipchat_ac_tenant" does not exist
LINE 1: ...", "sentry_hipchat_ac_tenant"."auth_user_id" FROM "sentry_hi...
                                                             ^

SQL: SELECT "sentry_hipchat_ac_tenant"."id", "sentry_hipchat_ac_tenant"."room_id", "sentry_hipchat_ac_tenant"."room_name", "sentry_hipchat_ac_tenant"."room_owner_id", "sentry_hipchat_ac_tenant"."room_owner_name", "sentry_hipchat_ac_tenant"."secret", "sentry_hipchat_ac_tenant"."homepage", "sentry_hipchat_ac_tenant"."token_url", "sentry_hipchat_ac_tenant"."capabilities_url", "sentry_hipchat_ac_tenant"."api_base_url", "sentry_hipchat_ac_tenant"."installed_from", "sentry_hipchat_ac_tenant"."auth_user_id" FROM "sentry_hipchat_ac_tenant" INNER JOIN "sentry_hipchat_ac_tenant_projects" ON ( "sentry_hipchat_ac_tenant"."id" = "sentry_hipchat_ac_tenant_projects"."tenant_id" ) WHERE "sentry_hipchat_ac_tenant_projects"."project_id" = %s 
`
It looks like the migration is not performed because there is no sentry_hipchat_ac_tenant table in database (dockerized postgreSQL).

**Comment by mattrobenolt** [comment]
You need to run `sentry upgrade` after installing the plugin again to get the new tables needed.

**Comment by ykravch** [comment]
I've run upgrade several times.
`Syncing...
Creating tables ...
Installing custom SQL ...
Installing indexes ...
Installed 0 object(s) from 0 fixture(s)

Synced:
 > django.contrib.admin
 > django.contrib.auth
 > django.contrib.contenttypes
 > django.contrib.messages
 > django.contrib.sessions
 > django.contrib.sites
 > django.contrib.staticfiles
 > captcha
 > crispy_forms
 > debug_toolbar
 > raven.contrib.django.raven_compat
 > rest_framework
 > sentry.plugins.sentry_interface_types
 > sentry.plugins.sentry_mail
 > sentry.plugins.sentry_urls
 > sentry.plugins.sentry_useragents
 > sentry.plugins.sentry_webhooks
 > south
 > sudo

Not synced (use migrations):
 - sentry
 - sentry.nodestore
 - sentry.search
 - social_auth
(use ./manage.py migrate to migrate these)
Running migrations for sentry:
- Nothing to migrate.
 - Loading initial data for sentry.
Installed 0 object(s) from 0 fixture(s)
Running migrations for nodestore:
- Nothing to migrate.
 - Loading initial data for nodestore.
Installed 0 object(s) from 0 fixture(s)
Running migrations for search:
- Nothing to migrate.
 - Loading initial data for search.
Installed 0 object(s) from 0 fixture(s)
Running migrations for social_auth:
- Nothing to migrate.
 - Loading initial data for social_auth.
Installed 0 object(s) from 0 fixture(s)
Forcing documentation sync
 - skipping, path cannot be written to: '/usr/local/lib/python2.7/site-packages/sentry/integration-docs'
Creating missing project keys
Correcting Group.num_comments counter`

**Comment by mattrobenolt** [comment]
That output just looks like the plugin isn't installed. What do you get from: `sentry plugins list` ?

**Comment by ykravch** [comment]
`root@sentry:~/SentryTest# docker run -it --rm -e SENTRY_SECRET_KEY='secret_key' --link sentry-postgres:postgres --link sentry-redis:redis ulli/myrepo:v2 plugins list
sentry-hipchat-ac 1.0.0`

**Comment by mattrobenolt** [comment]
I'll double check this today, but there shouldn't be anything fundamentally wrong here. But I'll confirm shortly.

**Comment by ykravch** [comment]
Hello.
Any updates?

**Comment by alejandrodnm** [comment]
I had to execute SENTRY_CONF=/etc/sentry sentry django migrate sentry_hipchat_ac in order to install the migrations.

**Comment by DenisBY** [comment]
I had same issue, but with pip installed sentry. Fixed it by @alejandrodnm solution.
