### ISSUE TITLE
404 on https://app.getsentry.com/_static/sentry/images/favicon.ico

### ISSUE THREAD

**Issue by rvanlieshout** [getsentry/sentry-hipchat-ac#29]
The default card uses https://app.getsentry.com/_static/sentry/images/favicon.ico, but it returns a 404

Can we restore this or do we need a different path?

**Comment by mattrobenolt** [comment]
I restored behavior for this on our side, but we definitely just shouldn't be hardcoding this URL since the URL has changed. So I'll leave this ticket open to address that.

Thanks for bringing it to our attention.
