### ISSUE TITLE
HipChat plugin missing configuration options

### ISSUE THREAD

**Issue by joelwigley** [getsentry/sentry-hipchat-ac#30]
I've installed the sentry_hipchat_ac plugin into a new Sentry 8.9.0 installation, however it's not working as expected.

The installation using 'pip' went fine, no errors were encountered. I then ran 'sentry upgrade' which completed without error too.

The problem is that when I go to a project -> Settings -> Integrations and click "configure plugin' under the HipChat plugin, there are no configuration options visible at all. I've attached a screenshot showing the problem. Note that enabling the plugin doesn't help, the same screen is displayed.

![sentry_hipchat_config](https://cloud.githubusercontent.com/assets/22139013/19375436/d2269ee2-921f-11e6-8c1a-1000622e1361.png)

I've tried running "sentry django migrate sentry_hipchat_ac" and then the "sentry upgrade" but it had no effect.

I have also installed the JIRA plugin and this worked correctly, the configuration screen has fields I can edit as expected.

If it helps, the output I'm getting from 'sentry upgrade' is:

```
# SENTRY_CONF=/etc/sentry sentry upgrade
Syncing...
Creating tables ...
Installing custom SQL ...
Installing indexes ...
Installed 0 object(s) from 0 fixture(s)

Synced:
 > django.contrib.admin
 > django.contrib.auth
 > django.contrib.contenttypes
 > django.contrib.messages
 > django.contrib.sessions
 > django.contrib.sites
 > django.contrib.staticfiles
 > crispy_forms
 > debug_toolbar
 > raven.contrib.django.raven_compat
 > rest_framework
 > sentry.plugins.sentry_interface_types
 > sentry.plugins.sentry_mail
 > sentry.plugins.sentry_urls
 > sentry.plugins.sentry_useragents
 > sentry.plugins.sentry_webhooks
 > south
 > sudo

Not synced (use migrations):
 - sentry
 - sentry.nodestore
 - sentry.search
 - social_auth
(use ./manage.py migrate to migrate these)
Running migrations for sentry:
- Nothing to migrate.
 - Loading initial data for sentry.
Installed 0 object(s) from 0 fixture(s)
Running migrations for nodestore:
- Nothing to migrate.
 - Loading initial data for nodestore.
Installed 0 object(s) from 0 fixture(s)
Running migrations for search:
- Nothing to migrate.
 - Loading initial data for search.
Installed 0 object(s) from 0 fixture(s)
Running migrations for social_auth:
- Nothing to migrate.
 - Loading initial data for social_auth.
Installed 0 object(s) from 0 fixture(s)
Creating missing DSNs
Correcting Group.num_comments counter
```

**Comment by dcramer** [comment]
You'll want to take a look at the sentry-plugins repo, which we've migrated this to. It's going to be a bit complex in that theres dupe migrations you need to eithr remove or skip manually.

**Comment by joelwigley** [comment]
I actually did that originally. Have a look at this issue on the new repository: https://github.com/getsentry/sentry-plugins/issues/42

I was unable to install the plugin from the new repository as it apparently requires a build of Sentry currently in development. The advice was to use this older repository for now.

**Comment by dcramer** [comment]
Unfortunately that advice is wrong. This repo is no longer compatible with 8.9. We haven't yet tagged a version of sentry-plugins, and I'm not 100% sure that master works flawlessly against 8.9, but HipChat should at least.
